language: python
python: 
  - "3.8"

addons:
  firefox: latest

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - mkdir /home/travis/.wdm/drivers/geckodriver/v0.26.0/linux64/
  - cd /home/travis/.wdm/drivers/geckodriver/v0.26.0/linux64/
  - tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
  - 'pip install pipenv'
  - 'pipenv sync'
  - "pip install -r requirements.txt"
  
# command to run tests
script:
  - "python manage.py makemigrations"
  - "python manage.py test apps/core/tests"